### ISSUE TITLE
Building image on Mac

### ISSUE THREAD

**Issue by swangcs** [lcodeca/rllibsumodocker#1]
I tried to build a docker image on my Mac using:

```
rllibsumodocker % bash docker-cmd.sh --build --cache --no-gpu --run
```

It runs good for the first few minutes, then stops with the following error info:
```
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.6/dist-packages (from beautifulsoup4->google->ray[tune]) (2.0.1)
Removing intermediate container 215b4de35b14
 ---> a6594cdebd4f
Step 14/40 : RUN groupadd --gid ${GROUP_ID} alice &&     useradd -m -s /bin/bash -u ${USER_ID} -g ${GROUP_ID} alice &&     echo "alice:alice" | chpasswd && adduser alice sudo
 ---> Running in fd2f12dd5f60
groupadd: GID '20' already exists
The command '/bin/bash -c groupadd --gid ${GROUP_ID} alice &&     useradd -m -s /bin/bash -u ${USER_ID} -g ${GROUP_ID} alice &&     echo "alice:alice" | chpasswd && adduser alice sudo' returned a non-zero code: 4
```

I've found two relevant discussions by searching google:
- about `groupadd:GID'20' already exists`: https://github.com/juliohm1978/dockerbb/issues/1
- about `create gid for OSX in Dockerfile`: https://github.com/pyro-ppl/pyro/pull/719

Seems the Dockerfile needs to be adapted a bit to be built on Mac OS. Could you @lcodeca please have a look and share some of your thoughts as to what changes need to be made? Many thanks.

**Comment by lcodeca** [comment]
The links you found are from similar errors but you can find the correct explanation here [https://stackoverflow.com/questions/43097341/docker-on-macosx-does-not-translate-file-ownership-correctly-in-volumes](https://stackoverflow.com/questions/43097341/docker-on-macosx-does-not-translate-file-ownership-correctly-in-volumes) is the problem.
The reason why you need a link between the user on your machine and the one in the docker is to mount devel and learning folders with the right privileges. 
The way I use it is to have my development code in devel, and all the results in the learning folder, always in sync between my host and the container.
I'm going to see if there is something that I can find about it, but without a Mac OS, I cannot help you that much.

**Comment by swangcs** [comment]
Thanks for your hint @lcodeca . I will follow your suggestions and try to modify Dockerfile to see if it can be built on Mac OS.

**Comment by lcodeca** [comment]
Before changing the docker file, I would check how to do the same thing I do on Linux, on your Mac OS. The problem is not building the image, it's to have your user id matched in the container. Maybe you can pass the proper uid instead of using the script to retrieve it automagically.

**Comment by swangcs** [comment]
Problem solved by changing a different ``gid`` (222) and ``uid`` (502) in the ``Dockerfile`` :)

Then I can build the docker image, run the sample code, and synchronize the folder inside docker container with my local Mac machine.
